export interface Drone {
  id: number;
  manufacturer: string;
  model: string;
  type: string;
  weight_lbs: number;
  flight_time_min: number;
  max_speed_mph: number;
  range_mi: number;
  payload_lbs: number;
  mission: string;
  group: number;
  tethered: boolean;
  desc: string;
  hot_endurance_min: number;
  hot_range_mi: number;
  hot_speed_mph: number;
  power_source: string;
  operating_temp_max_c: number;
}

/*
 * Hot-weather performance estimates (>45 C / 113 F):
 *
 * Battery-powered multirotors: ~15-20% endurance reduction.
 *   LiPo batteries experience accelerated internal resistance at high temps.
 *   Per ScienceDirect (2020), flight performance at 60C sees "little effect"
 *   short-term but significant capacity degradation. We model 15-18% for
 *   platforms rated to 49C+, 20% for those rated lower.
 *
 * Hybrid gas-electric (Skyfront, Edge Autonomy, K1000ULE):
 *   ~8-12% reduction. ICE engines lose some volumetric efficiency in thin
 *   hot air; generator output stable. Modeled at 10%.
 *
 * Heavy-fuel turbine (V-BAT): ~5-8% reduction. JP-5 engines are designed
 *   for wide temp ranges. Modeled at 7%.
 *
 * Tethered (Spectre): Minimal impact, continuous power. 0% reduction.
 *
 * FPV (short flights <15 min): ~10-12% reduction. Short duration limits
 *   cumulative heat exposure. Modeled at 10%.
 *
 * Fixed-wing cruise platforms: ~12-15% reduction. More efficient
 *   aerodynamics partially offset battery losses.
 */

export const DRONES: Drone[] = [
  { id: 1, manufacturer: "AeroVironment", model: "Red Dragon", type: "Fixed Wing", weight_lbs: 44, flight_time_min: 360, max_speed_mph: 100, range_mi: 248, payload_lbs: 22, mission: "One-Way Attack", group: 3, tethered: false, desc: "Fully autonomous loitering munition for GPS-denied environments. Modular payload bay with EFP warhead. AVACORE software with SPOTR-Edge target detection. Combat-proven, swarmable at 5 launches/min.", hot_endurance_min: 306, hot_range_mi: 210, hot_speed_mph: 95, power_source: "Battery", operating_temp_max_c: 49 },
  { id: 2, manufacturer: "AgEagle Aerial Systems", model: "eBee VISION", type: "Fixed Wing", weight_lbs: 4, flight_time_min: 100, max_speed_mph: 50, range_mi: 12, payload_lbs: 0.5, mission: "ISR", group: 1, tethered: false, desc: "Lightweight ISR fixed-wing with 32x zoom RGB and thermal sensors. AES-256 encrypted link. 3-min deploy. Silent mode. GNSS-denied capable. Service temp rated to 49C.", hot_endurance_min: 85, hot_range_mi: 10, hot_speed_mph: 48, power_source: "Battery", operating_temp_max_c: 49 },
  { id: 3, manufacturer: "AgEagle Aerial Systems", model: "eBee TAC", type: "Fixed Wing", weight_lbs: 3.5, flight_time_min: 90, max_speed_mph: 50, range_mi: 34, payload_lbs: 0.5, mission: "Mapping", group: 1, tethered: false, desc: "Tactical mapping drone with RTK/PPK accuracy to 1.5 cm. Maps up to 500 hectares per flight. MGRS-enabled, CivTAK/ATAK compatible. Service temp rated to 49C.", hot_endurance_min: 77, hot_range_mi: 29, hot_speed_mph: 48, power_source: "Battery", operating_temp_max_c: 49 },
  { id: 4, manufacturer: "Anduril Industries", model: "Ghost", type: "Single Rotor VTOL", weight_lbs: 42, flight_time_min: 60, max_speed_mph: 55, range_mi: 10, payload_lbs: 10, mission: "ISR", group: 2, tethered: false, desc: "Portable single-rotor VTOL for ISR, targeting, and force protection. Lattice AI platform automates mission planning. Rail-centric modular design.", hot_endurance_min: 49, hot_range_mi: 8, hot_speed_mph: 52, power_source: "Battery", operating_temp_max_c: 43 },
  { id: 5, manufacturer: "Anduril Industries", model: "Ghost-X", type: "Single Rotor VTOL", weight_lbs: 55, flight_time_min: 85, max_speed_mph: 55, range_mi: 15, payload_lbs: 25, mission: "ISR", group: 2, tethered: false, desc: "Extended-range Ghost with dual batteries and vision-based GNSS-denied navigation. Selected for Army MRR and Replicator 1.2. Weatherized for harsh environments.", hot_endurance_min: 70, hot_range_mi: 12, hot_speed_mph: 52, power_source: "Battery", operating_temp_max_c: 49 },
  { id: 6, manufacturer: "Ascent AeroSystems", model: "Spirit", type: "Coaxial VTOL", weight_lbs: 12.5, flight_time_min: 53, max_speed_mph: 60, range_mi: 12, payload_lbs: 9.5, mission: "All-Weather ISR", group: 2, tethered: false, desc: "All-weather coaxial UAS rated for rain, sleet, snow, and sand. Backpack-portable. MOSA-ready modular architecture. 75% smaller than comparable multirotors.", hot_endurance_min: 44, hot_range_mi: 10, hot_speed_mph: 57, power_source: "Battery", operating_temp_max_c: 50 },
  { id: 7, manufacturer: "Auterion", model: "SLM-10", type: "Quadcopter", weight_lbs: 4, flight_time_min: 30, max_speed_mph: 40, range_mi: 6, payload_lbs: 1.5, mission: "Swarm / ISR", group: 1, tethered: false, desc: "Skynode S reference design. Nemyx swarm-capable via software update. AuterionOS with PX4 autopilot. Designed for mass production and coordinated AI operations.", hot_endurance_min: 24, hot_range_mi: 5, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 8, manufacturer: "Easy Aerial", model: "Osprey (Free Flight)", type: "Quadcopter", weight_lbs: 15, flight_time_min: 30, max_speed_mph: 35, range_mi: 5, payload_lbs: 5, mission: "ISR", group: 2, tethered: false, desc: "Multi-rotor ISR platform with autonomous capabilities. Free flight variant for untethered patrol and surveillance. Also available tethered.", hot_endurance_min: 25, hot_range_mi: 4, hot_speed_mph: 33, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 9, manufacturer: "Easy Aerial", model: "Sparrow (Free Flight)", type: "Quadcopter", weight_lbs: 4, flight_time_min: 25, max_speed_mph: 30, range_mi: 3, payload_lbs: 1.5, mission: "ISR", group: 1, tethered: false, desc: "Compact free-flight quadcopter for rapid deployment ISR. Lightweight and portable for dismounted operations.", hot_endurance_min: 20, hot_range_mi: 2.5, hot_speed_mph: 28, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 10, manufacturer: "Edge Autonomy", model: "VXE30 Stalker", type: "Hybrid VTOL", weight_lbs: 30, flight_time_min: 480, max_speed_mph: 45, range_mi: 60, payload_lbs: 8, mission: "Long-Endurance ISR", group: 2, tethered: false, desc: "Hybrid VTOL with solid oxide fuel cell for 12+ hr endurance. Near-silent. Modular field-swappable payloads including EO/IR and laser designator.", hot_endurance_min: 432, hot_range_mi: 54, hot_speed_mph: 43, power_source: "Hybrid Fuel Cell", operating_temp_max_c: 50 },
  { id: 11, manufacturer: "FlightWave Aerospace", model: "Edge 130", type: "VTOL Fixed Wing", weight_lbs: 3, flight_time_min: 60, max_speed_mph: 50, range_mi: 12, payload_lbs: 1, mission: "ISR / Mapping", group: 1, tethered: false, desc: "Lightweight VTOL transition fixed-wing. Hand-launchable with efficient cruise for wide-area surveillance and linear infrastructure inspection.", hot_endurance_min: 50, hot_range_mi: 10, hot_speed_mph: 47, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 12, manufacturer: "Freefly Systems", model: "Astro/Max", type: "Quadcopter", weight_lbs: 7.8, flight_time_min: 43, max_speed_mph: 45, range_mi: 12, payload_lbs: 6.6, mission: "Mapping / Inspection", group: 1, tethered: false, desc: "Compact industrial platform with Smart Dovetail payload system. 7010 motors, 21-inch props. RTK-ready with Auterion Skynode. IP43 rated.", hot_endurance_min: 35, hot_range_mi: 10, hot_speed_mph: 43, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 13, manufacturer: "Freefly Systems", model: "Alta X – Blue Package", type: "Octocopter", weight_lbs: 20.5, flight_time_min: 50, max_speed_mph: 40, range_mi: 8, payload_lbs: 35, mission: "Heavy Lift", group: 2, tethered: false, desc: "Heavy-lift octocopter for cinema cameras, LiDAR, and multi-sensor payloads. Top and bottom mounting. NDAA/Blue package.", hot_endurance_min: 40, hot_range_mi: 6.5, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 14, manufacturer: "Hoverfly Technologies", model: "Spectre", type: "Tethered", weight_lbs: 35, flight_time_min: 9999, max_speed_mph: 0, range_mi: 0, payload_lbs: 8, mission: "Persistent ISR", group: 2, tethered: true, desc: "First and only tethered UAS on Blue list. Unlimited flight time via tethered power. Persistent ISR, on-the-move ops, and variable height antenna deployment.", hot_endurance_min: 9999, hot_range_mi: 0, hot_speed_mph: 0, power_source: "Tethered AC", operating_temp_max_c: 50 },
  { id: 15, manufacturer: "Inspired Flight", model: "IF800", type: "Quadcopter", weight_lbs: 12, flight_time_min: 54, max_speed_mph: 49, range_mi: 10, payload_lbs: 6.6, mission: "Mapping / Inspection", group: 2, tethered: false, desc: "Foldable quadcopter with dual hot-swappable batteries. Universal payload interface for EO/IR, LiDAR, photogrammetry. IP43. Blue and Green UAS certified.", hot_endurance_min: 44, hot_range_mi: 8, hot_speed_mph: 46, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 16, manufacturer: "Inspired Flight", model: "IF1200A", type: "Hexacopter", weight_lbs: 35, flight_time_min: 37, max_speed_mph: 40, range_mi: 8, payload_lbs: 18, mission: "Heavy Lift / Mapping", group: 2, tethered: false, desc: "Heavy-lift hexacopter for demanding enterprise missions. Payload-agnostic modular design. Blue and Green UAS certified.", hot_endurance_min: 30, hot_range_mi: 6.5, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 17, manufacturer: "Kraus Hamdani Aerospace", model: "K1000ULE", type: "Fixed Wing", weight_lbs: 55, flight_time_min: 480, max_speed_mph: 65, range_mi: 150, payload_lbs: 15, mission: "Long-Endurance ISR", group: 3, tethered: false, desc: "Ultra long-endurance fixed-wing for persistent wide-area surveillance. Large payload capacity for advanced ISR sensor packages.", hot_endurance_min: 432, hot_range_mi: 135, hot_speed_mph: 62, power_source: "Hybrid/Gas", operating_temp_max_c: 50 },
  { id: 18, manufacturer: "ModalAI", model: "Seeker Vision FPV", type: "FPV Quadcopter", weight_lbs: 0.55, flight_time_min: 15, max_speed_mph: 50, range_mi: 2, payload_lbs: 0.2, mission: "FPV Recon", group: 1, tethered: false, desc: "Micro FPV reconnaissance drone with VOXL 2 autonomy. GPS-denied navigation. Extremely low SWaP.", hot_endurance_min: 13, hot_range_mi: 1.7, hot_speed_mph: 47, power_source: "Battery", operating_temp_max_c: 43 },
  { id: 19, manufacturer: "ModalAI", model: "Stinger Vision FPV", type: "FPV Quadcopter", weight_lbs: 0.35, flight_time_min: 12, max_speed_mph: 45, range_mi: 1.5, payload_lbs: 0.1, mission: "FPV Recon", group: 1, tethered: false, desc: "Ultra-lightweight FPV nano drone with AI vision. Indoor/outdoor with obstacle avoidance. Secure digital link.", hot_endurance_min: 10, hot_range_mi: 1.3, hot_speed_mph: 42, power_source: "Battery", operating_temp_max_c: 43 },
  { id: 20, manufacturer: "Mountain Horse Solutions", model: "Talon DT-300", type: "Quadcopter", weight_lbs: 20, flight_time_min: 45, max_speed_mph: 45, range_mi: 10, payload_lbs: 8, mission: "ISR / Delivery", group: 2, tethered: false, desc: "Rugged multi-rotor for ISR and tactical delivery. Designed for austere environment operations.", hot_endurance_min: 37, hot_range_mi: 8, hot_speed_mph: 42, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 21, manufacturer: "Neros Technologies", model: "Archer", type: "Multi-Rotor", weight_lbs: 15, flight_time_min: 35, max_speed_mph: 40, range_mi: 8, payload_lbs: 5, mission: "ISR", group: 2, tethered: false, desc: "Multi-rotor ISR platform with ATO on Blue UAS list. Completed verification process.", hot_endurance_min: 28, hot_range_mi: 6.5, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 22, manufacturer: "Neros Technologies", model: "Archer Fiber", type: "Multi-Rotor", weight_lbs: 15, flight_time_min: 35, max_speed_mph: 40, range_mi: 5, payload_lbs: 5, mission: "ISR (Fiber Optic)", group: 2, tethered: false, desc: "Fiber-optic variant immune to RF jamming. Physical data link for contested EM environments.", hot_endurance_min: 28, hot_range_mi: 4, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 23, manufacturer: "Parrot", model: "ANAFI UKR", type: "Quadcopter", weight_lbs: 1.1, flight_time_min: 30, max_speed_mph: 34, range_mi: 2.5, payload_lbs: 0, mission: "ISR", group: 1, tethered: false, desc: "Compact tactical ISR quadcopter extensively fielded in Ukraine. Ultra-portable with thermal and EO cameras.", hot_endurance_min: 24, hot_range_mi: 2, hot_speed_mph: 32, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 24, manufacturer: "Parrot", model: "ANAFI USA GOV/MIL", type: "Quadcopter", weight_lbs: 1.1, flight_time_min: 32, max_speed_mph: 34, range_mi: 2.5, payload_lbs: 0, mission: "ISR", group: 1, tethered: false, desc: "Gov/Mil edition with 32x zoom and FLIR Boson thermal. AES-256 encrypted. No telemetry to manufacturer.", hot_endurance_min: 26, hot_range_mi: 2, hot_speed_mph: 32, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 25, manufacturer: "PDW", model: "C100", type: "Multi-Rotor", weight_lbs: 20, flight_time_min: 74, max_speed_mph: 45, range_mi: 6, payload_lbs: 10, mission: "ISR / Munition Drop", group: 2, tethered: false, desc: "Selected with Ghost-X for Army company-level sUAS. Backpack portable. ISR and munition delivery. 3-day training.", hot_endurance_min: 60, hot_range_mi: 5, hot_speed_mph: 42, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 26, manufacturer: "Quantum Systems", model: "Vector", type: "VTOL Fixed Wing", weight_lbs: 18.7, flight_time_min: 120, max_speed_mph: 44, range_mi: 22, payload_lbs: 3, mission: "ISR / Mapping", group: 2, tethered: false, desc: "VTOL transition fixed-wing, 2-in-1 multicopter config. Encrypted mesh IP to 15+ km. Motor-off silent glide. Combat-proven in Ukraine. AI onboard.", hot_endurance_min: 100, hot_range_mi: 18, hot_speed_mph: 42, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 27, manufacturer: "Red Cat", model: "Fang F7", type: "FPV Quadcopter", weight_lbs: 2, flight_time_min: 12, max_speed_mph: 80, range_mi: 3, payload_lbs: 1.5, mission: "FPV", group: 1, tethered: false, desc: "NDAA-compliant 7-inch FPV drone. Retrievable and reusable. Lowest-cost NDAA FPV family. Carbon fiber frame.", hot_endurance_min: 10, hot_range_mi: 2.5, hot_speed_mph: 75, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 28, manufacturer: "Renegade UxS", model: "Nightmare", type: "FPV Quadcopter", weight_lbs: 2.5, flight_time_min: 15, max_speed_mph: 75, range_mi: 3, payload_lbs: 1.5, mission: "FPV", group: 1, tethered: false, desc: "Analog FPV for high-speed tactical ops. Rugged frame. NDAA-compliant.", hot_endurance_min: 13, hot_range_mi: 2.5, hot_speed_mph: 70, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 29, manufacturer: "Renegade UxS", model: "Nightmare Digital", type: "FPV Quadcopter", weight_lbs: 2.5, flight_time_min: 15, max_speed_mph: 75, range_mi: 4, payload_lbs: 1.5, mission: "FPV", group: 1, tethered: false, desc: "Digital video variant with enhanced link quality and range over analog.", hot_endurance_min: 13, hot_range_mi: 3.5, hot_speed_mph: 70, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 30, manufacturer: "Shield AI", model: "V-BAT", type: "VTOL Ducted Fan", weight_lbs: 125, flight_time_min: 780, max_speed_mph: 90, range_mi: 350, payload_lbs: 40, mission: "ISR / Targeting", group: 3, tethered: false, desc: "Ducted-fan VTOL with 13+ hr JP-5 heavy-fuel endurance. Hivemind AI pilot. Deployed with all 7 MEUs and USCG. MQ-35A. Swarm-capable.", hot_endurance_min: 725, hot_range_mi: 325, hot_speed_mph: 87, power_source: "Heavy Fuel (JP-5)", operating_temp_max_c: 52 },
  { id: 31, manufacturer: "Skydio", model: "X10D", type: "Quadcopter", weight_lbs: 5, flight_time_min: 40, max_speed_mph: 38, range_mi: 7, payload_lbs: 0.5, mission: "Autonomous ISR", group: 1, tethered: false, desc: "AI autonomy with 6 nav cameras, 360-degree obstacle avoidance. 48MP telephoto, FLIR Boson+. NightSense. Blackout mode. IP55. 40-sec deploy.", hot_endurance_min: 33, hot_range_mi: 5.8, hot_speed_mph: 36, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 32, manufacturer: "Skyfront", model: "Perimeter 8", type: "Hybrid Octocopter", weight_lbs: 55, flight_time_min: 780, max_speed_mph: 35, range_mi: 100, payload_lbs: 22, mission: "Long-Endurance ISR", group: 3, tethered: false, desc: "Hybrid gas-electric octocopter. World record 13 hr / 205 mi flight. Options for 50C+ operations.", hot_endurance_min: 702, hot_range_mi: 90, hot_speed_mph: 33, power_source: "Hybrid Gas-Electric", operating_temp_max_c: 50 },
  { id: 33, manufacturer: "Teal (Red Cat)", model: "Teal 2", type: "Quadcopter", weight_lbs: 2.75, flight_time_min: 30, max_speed_mph: 23, range_mi: 3, payload_lbs: 0.5, mission: "Night ISR", group: 1, tethered: false, desc: "Compact night-optimized ISR drone. Dual-axis EO/IR gimbal with FLIR Hadron 640R thermal sensor.", hot_endurance_min: 24, hot_range_mi: 2.5, hot_speed_mph: 22, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 34, manufacturer: "Teledyne FLIR", model: "Black Hornet 4", type: "Nano Single Rotor", weight_lbs: 0.15, flight_time_min: 30, max_speed_mph: 13, range_mi: 1.9, payload_lbs: 0, mission: "Covert ISR", group: 1, tethered: false, desc: "70-gram nano PRS. 12MP EO and thermal. GPS-denied. 25-knot wind rated. 30-sec deploy. 20,000+ delivered to 40+ nations.", hot_endurance_min: 24, hot_range_mi: 1.5, hot_speed_mph: 12, power_source: "Battery", operating_temp_max_c: 43 },
  { id: 35, manufacturer: "Thunder Tiger Corp.", model: "Overkill FPV", type: "FPV Quadcopter", weight_lbs: 2, flight_time_min: 14, max_speed_mph: 70, range_mi: 3, payload_lbs: 1, mission: "FPV", group: 1, tethered: false, desc: "Ruggedized FPV for tactical ops. NDAA-compliant with high-speed maneuverability.", hot_endurance_min: 12, hot_range_mi: 2.5, hot_speed_mph: 66, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 36, manufacturer: "Titan Dynamics", model: "Raptor", type: "Multi-Rotor", weight_lbs: 15, flight_time_min: 45, max_speed_mph: 45, range_mi: 10, payload_lbs: 5, mission: "ISR / Delivery", group: 2, tethered: false, desc: "Versatile multi-rotor for ISR and payload delivery. Rapid deployment for tactical scenarios.", hot_endurance_min: 37, hot_range_mi: 8, hot_speed_mph: 42, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 37, manufacturer: "Vantage Robotics", model: "Trace", type: "Quadcopter", weight_lbs: 3.5, flight_time_min: 30, max_speed_mph: 35, range_mi: 5, payload_lbs: 0.5, mission: "ISR", group: 1, tethered: false, desc: "Compact, quiet reconnaissance quadcopter. Foldable, backpack-portable. Rapid tactical deployment.", hot_endurance_min: 24, hot_range_mi: 4, hot_speed_mph: 33, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 38, manufacturer: "Vantage Robotics", model: "Vesper", type: "Quadcopter", weight_lbs: 4, flight_time_min: 45, max_speed_mph: 40, range_mi: 7, payload_lbs: 1, mission: "ISR", group: 1, tethered: false, desc: "Extended-endurance variant with improved range and EO/IR sensors for persistent surveillance.", hot_endurance_min: 37, hot_range_mi: 5.8, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 39, manufacturer: "Wingtra", model: "WingtraOne Gen II", type: "VTOL Fixed Wing", weight_lbs: 9, flight_time_min: 59, max_speed_mph: 36, range_mi: 20, payload_lbs: 2, mission: "Survey Mapping", group: 1, tethered: false, desc: "VTOL survey drone with 61MP camera. PPK GNSS for 1cm accuracy without GCPs. Vertical launch and landing in confined spaces.", hot_endurance_min: 49, hot_range_mi: 17, hot_speed_mph: 34, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 40, manufacturer: "Wingtra", model: "WingtraRAY", type: "VTOL Fixed Wing", weight_lbs: 18, flight_time_min: 90, max_speed_mph: 40, range_mi: 30, payload_lbs: 4, mission: "Large-Area Mapping", group: 2, tethered: false, desc: "Next-gen large-area mapping VTOL. Extended coverage with professional LiDAR and photogrammetry.", hot_endurance_min: 75, hot_range_mi: 25, hot_speed_mph: 38, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 41, manufacturer: "Zepher Flight Labs", model: "Z1", type: "Multi-Rotor", weight_lbs: 5, flight_time_min: 30, max_speed_mph: 35, range_mi: 5, payload_lbs: 1, mission: "ISR", group: 1, tethered: false, desc: "Compact multi-rotor for tactical ISR. Selected at Blue UAS Refresh Challenge at 29 Palms.", hot_endurance_min: 24, hot_range_mi: 4, hot_speed_mph: 33, power_source: "Battery", operating_temp_max_c: 45 },
  { id: 42, manufacturer: "Zone 5 Technologies", model: "Paladin", type: "Fixed Wing", weight_lbs: 15, flight_time_min: 90, max_speed_mph: 55, range_mi: 40, payload_lbs: 3, mission: "ISR / Mapping", group: 2, tethered: false, desc: "Fixed-wing ISR platform with ATO. Completed Blue UAS verification process. Efficient long-range reconnaissance.", hot_endurance_min: 75, hot_range_mi: 33, hot_speed_mph: 52, power_source: "Battery", operating_temp_max_c: 45 },
];

export function formatTime(min: number): string {
  if (min >= 9999) return "UNLIMITED";
  if (min >= 60) {
    const h = Math.floor(min / 60);
    const m = min % 60;
    return m > 0 ? `${h}h ${m}m` : `${h}h`;
  }
  return `${min}m`;
}
